CourseKnowledge-main/DatabasesProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^theapp/', include('theapp.urls')),
]

CourseKnowledge-main/theapp/urls.py
from django.conf.urls import url
from . import views

# app_name is a namespace so we can reuse index and detail in other apps
app_name = 'theapp'

urlpatterns = [
	# /theapp/
    url(r'^$', views.index, name='index'),

    # /theapp/1234/
    # navigate to a view of school_id 1234
    url(r'^(?P<school_id>[0-9]+)/$', views.detail, name='detail'),

    # /theapp/school/add/
    url(r'school/add/$', views.SchoolCreate.as_view(), name='school-add'),

    ##TEST CODE SHIV
    #/theapp/student/add/
    url(r'student/add/$', views.StudentCreate.as_view(), name='student-add')
]

CourseKnowledge-main/theapp/models.py
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models

# this is gonna translate exactly to our database.

class School(models.Model):
	schoolID = models.IntegerField(primary_key = True)
	schoolname = models.CharField(max_length=50)
	address = models.CharField(max_length=50)

	def get_absolute_url(self):
		return reverse('theapp:index')

	# defines what string printout of this table should look like
	def __str__(self):
		return str(self.schoolID).decode("utf-8") + ' - ' + self.schoolname + ' - ' + self.address
		# needed to cast schoolID to unicode since it is an integer.

class Student(models.Model):
	studentID = models.IntegerField(primary_key = True)
	# set school_id when setting the school key
	school = models.ForeignKey(School, on_delete=models.CASCADE)
	GPA = models.FloatField()
	name = models.CharField(max_length=100)

	def __str__(self):
		return str(self.studentID).decode("utf-8")+ ' - ' + self.name + ' - '  + str(self.school_id).decode("utf-8") + ' - ' + str(self.GPA).decode("utf-8")

class Professor(models.Model):
	profID = models.IntegerField(primary_key = True)
	profname = models.CharField(max_length=50)
	dept = models.CharField(max_length=50)

	def __str__(self):
		return str(self.profID).decode("utf-8") + ' - ' + self.profname + ' - ' + self.dept


class Course(models.Model):
	courseID = models.IntegerField(primary_key = True)
	prof = models.ForeignKey(Professor, on_delete=models.CASCADE)
	coursename = models.CharField(max_length=50)
	credits = models.IntegerField()

	def __str__(self):
		return str(self.courseID).decode("utf-8") + ' - ' + self.coursename + ' - ' + str(self.credits).decode("utf-8") + ' - ' + str(self.prof_id).decode("utf-8")

class EnrollsIn(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	date = models.DateField()
	grade = models.FloatField()

	def __str__(self):
		return str(self.student_id).decode("utf-8") + ' - ' + str(self.course_id).decode("utf-8") + ' - ' + str(self.date).decode("utf-8") + ' - ' + str(self.grade).decode("utf-8")

# Will need to add frienship class later on for advanced functions

CourseKnowledge-main/theapp/views.py
from django.http import Http404
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Student
from .models import School


def index(request):
    all_schools = School.objects.all()
    # create dictionary
    context = {
        'all_schools': all_schools,
    }
    return render(request, 'theapp/index.html', context)


"""
class IndexView(generic.ListView):
	template_name = 'theapp/index.html'
	context_object_name = 'all_schools'

	def get_queryset(self):
		return School.objects.all()
"""


def detail(request, school_id):
    try:
        school = School.objects.get(pk=school_id)  # check database for the school_id passed in
    except School.DoesNotExist:
        raise Http404("School not in Database")
    return render(request, 'theapp/detail.html', {'school': school, })


class SchoolCreate(CreateView):
    models = School
    fields = ['schoolID', 'schoolname', 'address']
    template_name = 'theapp/school_form.html'

    def get_queryset(self):
        return School.objects.all()


# TEST CODE SHIV
class StudentCreate(CreateView):
    models = Student
    fields = ['studentID', 'studentname', 'GPA']
    template_name = 'theapp/student_form.html'

    def get_queryset(self):
        return Student.objects.all()

CourseKnowledge-main/theapp/templates/theapp/detail.html
<!-- {{ school }} -->

<h1>Students attending {{school.schoolname}}:</h1>

<u1>
	{% for student in school.student_set.all %}
		<li>{{student.name}} - {{student.pk}} - {{student.GPA}}</li>
	{% endfor %}
</u1>

CourseKnowledge-main/theapp/templates/theapp/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{field.errors}}</span>
		</div>
		<label class="control-label col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10">{{field}}</div>
	</div>
{% endfor %}

CourseKnowledge-main/theapp/templates/theapp/index.html
{% if all_schools %}
	<h3>Schools:</h3>
	<u1>
		{% for school in all_schools %}
		<li><a href="{% url 'theapp:detail' school.pk %}">{{school.schoolname}}</a></li>
		<!-- Old code
			<li><a href="/theapp/{{ school.pk }}/">{{school.schoolname}}</a></li> 
		-->
		{% endfor %}
	</u1>
{% else %}
	<h3>No schools</h3>
{% endif %}

<li>
	<a href="{% url 'theapp:school-add' %}">
		Add
	</a>
</li>
	

CourseKnowledge-main/theapp/templates/theapp/school_form.html
<h1>Add a school:</h1>

<u1>
	Idk
</u1>

<div class="container-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'theapp/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>

	</div>

</div>

CourseKnowledge-main/theapp/templates/theapp/student_form.html
<h1>Add a Student:</h1>

<u1>
	Test
</u1>

<div class="container-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'theapp/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>

	</div>

</div>